# Generated by Django 3.2.18 on 2023-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_query_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='query',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
